[project]
name = "agent-plays-balatro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=11.2.1",
    "pyautogui>=0.9.54",
    "pydantic>=2.11.5",
    "pydantic-settings>=2.9.1",
    "smolagents[litellm]>=1.16.1",
]
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
